### ISSUE TITLE
Error when retrieving remote config version

### ISSUE THREAD

**Issue by wojteklu** [eBay/firebase-remote-config-monitor#3]
When fetching remote config I see that token is rejected with following error:
```
{"error":{"code":403,
"message":"[AUTHORIZATION_ERROR]: User does not have the following permission: GET_TEMPLATE",
"status":"PERMISSION_DENIED"}}
```

I can't find such permission in firebase settings. @frindly maybe you know how I can fix that?

**Comment by fezzab** [comment]
Was there any resolution for this? @wojteklu

**Comment by jbeuckm** [comment]
How did you solve this?

**Comment by fezzab** [comment]
Hi @jbeuckm 
are you trying from the client side or using a serviceaccount in functions?

**Comment by smmcdonald** [comment]
This 403 error happens because the author of this cloud function always uses the ApplicationDefault credentials. So, even if you manually specify using different account credentials when initializing the app e.g. 
```
var prodServiceAccount = require('./PROD.json');

admin.initializeApp({
  credential: admin.credential.cert(prodServiceAccount),
});
```
which is what I tried and got a 403 error since the access token only uses the default service account in **firebase_retreiver.js**.
```
function getAccessToken() {
    return admin.credential
       .applicationDefault()
       .getAccessToken()
  }
```
The only way I was able to get this working was to add the required permissions (cloudconfig.configs.get, cloudconfig.configs.update, and firebaseanalytics.resources.googleAnalyticsReadAndAnalyze) to the 'App Engine default service account'. For more information see: https://stackoverflow.com/questions/71472817/what-permissions-are-required-to-get-template-for-firebase-remote-config.
